server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/student/**