spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path= /account/**
          filters:
            - RewritePath=/account/(?<path>.*), /$\{path}
  application:
    name: api-gateway
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework: debug

